name: Continuous Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.2"

      - name: setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.4"

      - name: setup project dependencies
        run: poetry install

      - name: run quality jobs
        run: ./scripts/quality.sh

      - name: run unit tests and collect code coverage
        run: ./scripts/tests.sh

      - name: export project dependencies
        run: poetry export -f requirements.txt > requirements.txt

      - name: set runtime version
        run: echo "python-3.9.2" > runtime.txt
      
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
